trigger: 
- master 
pool: 
   vmImage: 'windows-latest'

steps:
- task: CredScan@2
  inputs:
   toolMajorVersion: 'V2'
- task: ESLint@1
  inputs:
   Configuration: 'recommended'
   TargetType: 'eslint'
   ErrorLevel: 'warn'

- task: Semmle@1
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)//MetaOptimize'
    language: 'C#'
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true
