trigger: 
- master 
pool: 
   vmImage: 'windows-latest'

steps:
- task: CredScan@2
  inputs:
   toolMajorVersion: 'V3'

- task: Semmle@1
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)//MetaOptimize'
    language: 'CSharp'
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true
